/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/polyjet.glb
Author: checkersai (https://sketchfab.com/checkersai)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-jet-mk2-f2d29714c8e24a2ba03fdde5fc4b20f8
Title: Low Poly Jet Mk.2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/polyjet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.003']} />
    </group>
  )
}

useGLTF.preload('/polyjet.glb')
